// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLbsLjKKKdzo3j6N_uMExN8msjJGUcjBE',
    appId: '1:587738909180:android:b751705ce4d40da05fca79',
    messagingSenderId: '587738909180',
    projectId: 'check-me-in-66fa7',
    storageBucket: 'check-me-in-66fa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfyZGL5_Oj3VCzaF6sga6vrtYGB1WfVy0',
    appId: '1:587738909180:ios:2bc130886424e3645fca79',
    messagingSenderId: '587738909180',
    projectId: 'check-me-in-66fa7',
    storageBucket: 'check-me-in-66fa7.appspot.com',
    iosBundleId: 'com.diseirang.checkMeIn',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFz3CSIR2JYimZmcGCvvX2RtIXZnN2q4',
    appId: '1:587738909180:web:c41805d1ddba03155fca79',
    messagingSenderId: '587738909180',
    projectId: 'check-me-in-66fa7',
    authDomain: 'check-me-in-66fa7.firebaseapp.com',
    storageBucket: 'check-me-in-66fa7.appspot.com',
  );

}